### ISSUE TITLE
RemoteBackup备份报错

### ISSUE THREAD

**Issue by me66ccff** [leeveel/GeekServer#18]
服务器使用内嵌数据库，使用RemoteBackup备份到本地mongo数据库报错，修改app_config.json文件的数据库模式为1能连上mongo数据库。

init NLog config...
2023-05-04 23:31:32.0584 INFO  进入游戏主循环...
***进入游戏主循环***
2023-05-04 23:31:32.5009 INFO  初始化MongoDB服务完成 Url:mongodb://127.0.0.1:27017/?authSource=admin
2023-05-04 23:31:32.5009 INFO  初始化备份任务完成
2023-05-04 23:31:32.5009 INFO  下次定时回存时间 2023/5/4 23:31:42
2023-05-04 23:31:42.6878 ERROR  StartNewTurn Throw Exception:MessagePack.MessagePackSerializationException: Failed to deserialize Geek.Server.Core.Storage.SaveTimestamp value.
 ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 146 (fixarray) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
   at MessagePack.MessagePackReader.ReadMapHeader()
   at MessagePack.Formatters.Geek_Server_Core_Storage_SaveTimestampFormatter1.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](ReadOnlyMemory`1 buffer, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at Geek.Server.Core.Serialize.Serializer.Deserialize[T](Byte[] data) in D:\Project\Unity3D\GeekServer\Geek.Server.Core\Serialize\Serializer.cs:line 13
   at Geek.Server.Core.Storage.DB.Table`1.Enumerator.MoveNext() in D:\Project\Unity3D\GeekServer\Geek.Server.Core\Storage\DB\Table.cs:line 192
   at Geek.Server.RemoteBackup.Logic.Backup.Start() in D:\Project\Unity3D\GeekServer\Geek.Server.RemoteBackup\Logic\Backup.cs:line 46
   at Geek.Server.RemoteBackup.Logic.BackupTask.StartNewTurn() in D:\Project\Unity3D\GeekServer\Geek.Server.RemoteBackup\Logic\BackupTask.cs:line 55
2023-05-04 23:31:42.6878 INFO  定时回存完成 耗时: 96.6496ms
2023-05-04 23:31:42.6878 INFO  下次定时回存时间 2023/5/4 23:34:42

**Comment by leeveel** [comment]
已修复
